// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtnTLx-RlaKVCNkElDA5Yzk-dCGJhw4mo',
    appId: '1:527070146420:web:9e7cd74aee104d98290621',
    messagingSenderId: '527070146420',
    projectId: 'flutter-chat-app-fb65b',
    authDomain: 'flutter-chat-app-fb65b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-fb65b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKsBIdoBHRCw2-Pq3uGeXqJhuEBY3K5Ak',
    appId: '1:527070146420:android:233c6e635dea2751290621',
    messagingSenderId: '527070146420',
    projectId: 'flutter-chat-app-fb65b',
    storageBucket: 'flutter-chat-app-fb65b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcHZivRlb3syNh0CEXV85r0zypZy-XqAc',
    appId: '1:527070146420:ios:c802a3bcb72fe1f2290621',
    messagingSenderId: '527070146420',
    projectId: 'flutter-chat-app-fb65b',
    storageBucket: 'flutter-chat-app-fb65b.appspot.com',
    iosClientId: '527070146420-7204ijui1gnmr18mcndv1o5he61nand8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
